// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using secondTask;

namespace secondTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200205094414_secondTask.AppDbContext")]
    partial class secondTaskAppDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("secondTask.model.Url", b =>
                {
                    b.Property<string>("Short")
                        .HasColumnType("character(8)")
                        .IsFixedLength(true)
                        .HasMaxLength(8);

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Short");

                    b.ToTable("url");
                });
#pragma warning restore 612, 618
        }
    }
}
